dim: 128
order: 2
num_heads: 16
inner_factor: 1
num_blocks: 1
fused_bias_fc: false
outer_mixing: false
dropout: 0
post_order_ffn: false
short_filter_order: 3
activation: 'id'
long_conv_cfg:
  num_heads: 16
  bias: true
  filter_cls: 'implicit'
  filter_cfg:
    order: 2